### ISSUE TITLE
error when server.js start ....

### ISSUE THREAD

**Issue by filPhil** [micklynch/travelbudget#6]
Hello Mick,

When i tried to run node server.js I have  this error : 

node server.js
/........................./tuto/travelbudget-master/node_modules/sequelize-typescript/lib/services/models.js:158
    throw new Error("Specified type of property '" + propertyName + "'\n            cannot be automatically resolved to a sequelize data type. Please\n            define the data type manually");
    ^

Error: Specified type of property 'country'
            cannot be automatically resolved to a sequelize data type. Please
            define the data type manually
    at Object.getSequelizeTypeByDesignType (/............................./tuto/travelbudget-master/node_modules/sequelize-typescript/lib/services/models.js:158:11)

Any ideas ?

Phil

**Comment by micklynch** [comment]
Hi Phil,

Sorry for my slow reply. Sounds like your DB may be empty. Can you use pgAdmin (or equivalent) to see if the DB exists and the entity is there?

If you follow my tutorial on Medium, I tried to explain how to populate initially. Have a look.

If you need to initialize the model in your DB, you can also uncomment these two lines:
https://github.com/micklynch/travelbudget/blob/c5e6d3a67f7c76fabdd66795c324d70424159396/src/server/database.ts#L22

And that will initialize your model and populate with some data.

I hope that helps,
Mick

**Comment by waijune118** [comment]
Hi Mick, 
I have run "node server.js" by uncommenting the initializeDatabase() and populateData(). However, I still receive the error message above. I hope that you can help me out. 

Thank you very much.
June

**Comment by hadoopcod** [comment]
Hi Mick,
I am facing the same issue. How to fix it?

Thank you.
Silvino

**Comment by hadoopcod** [comment]
Hi all, 

Issue solved by explicitly define the typescript datatype for each column as follow:
@Column(DataType.TEXT)
country: string;

@Column(DataType.FLOAT)
exchangerate: number;

@CreatedAt
 @Column(DataType.DATE)
 createdAt: Date;
@UpdatedAt
 @Column(DataType.DATE)
 updatedAt: Date;

I hope this helps!
Silvino
